### ISSUE TITLE
If no workers are specified gawp can't be stopped

### ISSUE THREAD

**Issue by vendion** [martingallagher/gawp#1]
Using a modified version of your example configuration file:

``` yaml
recursive: true           # Watch directories recursively
verbose: false            # Verbose logging

write, create, rename:    # Actionable events (supported: create, write, rename, remove, chmod)
  (?i)([a-z]+)\.src\.js$: # Rules are regular expression strings (https://code.google.com/p/re2/wiki/Syntax)
  - java -jar ~/compiler.jar -O=ADVANCED --language_in=ECMASCRIPT5_STRICT --formatting=SINGLE_QUOTES --define='DEBUG=false' --js_output_file=scripts/$1.js $file

  (?i)[a-z]+\.scss:
  - compass compile --boring --time -s compressed --css-dir styles/ $file
  - echo HELLO DENNIS!    # Rules can have multiple commands; output is written as-is to the Gawp log

create:
  .*:
  - echo created $file    # Rule submatches and file path can be accessed via $1, $2 ... $n (nth submatch) and $file

remove:
  .*:
  - echo removed $file
```

Trying to stop gawp with Ctrl-C does nothing, in order to stop it I had to get the PID and do `kill -9 $PID` to kill it.  Maybe gawp should detect issues like this and die with a configuration error.
